In [1]:
def test():
    print('test() for function')
    return
test()

test() for function


In [3]:
class demo:
    def test(self):
        print("test()for function")
        return
obj= demo()
obj.test()

test()for function


In [4]:
class demo1:
    def fact(self,n):
        #return the factorial
        return
    p1= demo1
    p1.fact(5)#120
    p1

NameError: name 'demo1' is not defined

In [12]:
class Demo1:
    def fact(self,n):
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact 
p1=Demo1()
print(p1.fact(5))

120


In [ ]:
class Demo2:
    def_init_(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add()

In [14]:
lst=[1,2,3,4]
print(lst)


[1, 2, 3, 4]


In [15]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [16]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
a1=np.array([1,2,9,4])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 9 4 4 5 6]


In [18]:
import numpy as np
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [19]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int64


In [21]:
import numpy as np
a1=np.random.normal(5,0.5,10)
print(a1)

[4.91880455 4.93268492 4.70081551 4.26144752 4.95248655 4.648351
 5.99119197 5.63240198 5.407024   4.28096839]


In [22]:
import numpy as np
np.zeros((2,2))


array([[0., 0.],
       [0., 0.]])

In [23]:
import numpy as np
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]])

In [24]:
import numpy as np
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [26]:
lst=[1.0,2.5,3.6,9.5]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
float64


In [30]:
import numpy as np
A = np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [31]:
import numpy as np
A = np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [33]:
import numpy as np
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [34]:
import numpy as np
a1=np.array([(1,2,3),(4,5,6)])
print("first row:",a1[0])

first row: [1 2 3]


In [35]:
import numpy as np
a1=np.array([(1,2,3),(4,5,6)])
print("second row:",a1[1])

second row: [4 5 6]
